apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/krishi0408/Gitops-Samples.git
        revision: main
        files:
          - path: ApplicationSet-Sample/cluster-config/*/config.json
  template:
    metadata:
      name: guestbook-{{ environment }}  # Creates app like guestbook-Gitops_Dev_Env
    spec:
      project: default
      source:
        repoURL: https://github.com/krishi0408/Gitops-Samples.git
        targetRevision: main
        path: ApplicationSet-Sample/apps/guestbook  # Uses guestbook app manifests
        helm:
          values: |
            cluster_name: in-cluster  # Same cluster for all
            harness_service: service_gitops_pr  # Same Harness service for all
            environment: {{ environment }}
            replicas: {{ replicas }}
      destination:
        server: "https://kubernetes.default.svc"  # Same cluster for all
        namespace: '{{ environment }}'  # Namespace changes dynamically
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
